// Generated by dia2code
#ifndef RENDER__ELEMENTTABLAYER__H
#define RENDER__ELEMENTTABLAYER__H


namespace status {
  class ElementTab;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "../../shared/status/ElementTab.h"

namespace render {

  /// class ElementTabLayer - 
  class ElementTabLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    status::ElementTab* element_tab;
    // Operations
  public:
    ElementTabLayer (status::ElementTab* element_tab);
    ~ElementTabLayer ();
    // Setters and Getters
  };

};

#endif
