// Generated by dia2code
#ifndef RENDER__GRIDTILESET__H
#define RENDER__GRIDTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace status {
  class Element;
};
namespace render {
  class TileSet;
}

#include "TileSet.h"

namespace render {

  /// class GridTileSet - 
  class GridTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<std::vector<Tile*>> lands;
    std::vector<std::vector<Tile*>> buildings;
    // Operations
  public:
    GridTileSet ();
    ~GridTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    std::string getImageFile () const;
    Tile* getTile (status::Element* element);
    // Setters and Getters
  };

};

#endif
