// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <vector>
#include <string>

namespace render {
  class TexturesPack;
};
namespace sf {
  class Sprite;
}

#include "TexturesPack.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  private:
    TexturesPack pack_textures;
    std::vector<std::vector<int> > layer_array;
    char* text_file_name;
    char* type_layer;
    int height;
    int width;
    int tile_height;
    int tile_width;
    std::vector<std::vector<sf::Sprite> > sprites;
    std::vector<std::string> image_tab_name;
    // Operations
  public:
    Layer (char* text_file_name, char* type_layer);
    void setLayerArray (char* text_file_name);
    void setSpritesPositions ();
    void display ();
    int getWidth () const;
    int getHeight () const;
    int getTile_width () const;
    int getTile_height () const;
    sf::Sprite getSprite (int i, int j) const;
    TexturesPack getTextures_pack () const;
    int getLayer_array (int i, int j) const;
    // Setters and Getters
  };

};

#endif
