// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

<<<<<<< HEAD
#include <vector>
#include <string>

namespace render {
  class TexturesPack;
};
namespace sf {
  class Sprite;
}

#include "TexturesPack.h"
=======
#include <string>

namespace render {
  class Surface;
  class TileSet;
}

#include "Surface.h"
#include "TileSet.h"
>>>>>>> 6c7cf3bd3aaf1838714150f0f4fd4f0eeb184a42

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
<<<<<<< HEAD
  private:
    TexturesPack pack_textures;
    std::vector<std::vector<int> > layer_array;
    char* text_file_name;
    char* type_layer;
    int height;
    int width;
    int tile_height;
    int tile_width;
    std::vector<std::vector<sf::Sprite> > sprites;
    std::vector<std::string> image_tab_name;
    // Operations
  public:
    Layer (char* text_file_name, char* type_layer);
    void setLayerArray (char* text_file_name);
    void setSpritesPositions ();
    void display ();
    int getWidth () const;
    int getHeight () const;
    int getTile_width () const;
    int getTile_height () const;
    sf::Sprite getSprite (int i, int j) const;
    TexturesPack getTextures_pack () const;
    int getLayer_array (int i, int j) const;
    // Setters and Getters
=======
  protected:
    Surface surface;
    TileSet* tileset;
    std::string text_file_name;
    std::string type_layer;
    int width;
    int height;
    int tile_width;
    int tile_height;
    // Operations
  public:
    Layer ();
    Layer (std::string text_file_name, std::string type_layer);
    virtual ~Layer ();
    Surface getSurface () const;
    void setSurface ();
    void getFileTextData (std::string& text_file_name);
    TileSet* getTileSet () const;
    int getWidth () const;
    int getHeight () const;
    // Setters and Getters
    const TileSet*& getTileset() const;
    void setTileset(const TileSet*& tileset);
    const std::string& getText_file_name() const;
    void setText_file_name(const std::string& text_file_name);
    const std::string& getType_layer() const;
    void setType_layer(const std::string& type_layer);
    void setWidth(int width);
    void setHeight(int height);
    int getTile_width() const;
    void setTile_width(int tile_width);
    int getTile_height() const;
    void setTile_height(int tile_height);
>>>>>>> 6c7cf3bd3aaf1838714150f0f4fd4f0eeb184a42
  };

};

#endif
