// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H


namespace status {
  class State;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "status/State.h"

namespace render {

  /// class StateLayer - 
  class StateLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    status::State* state;
    // Operations
  public:
    StateLayer (status::State* state);
    // Setters and Getters
  };

};

#endif
