// Generated by dia2code
#ifndef RENDER__STATETILESET__H
#define RENDER__STATETILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "TileSet.h"

namespace render {

  /// class StateTileSet - 
  class StateTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile*> chars;
    // Operations
  public:
    StateTileSet ();
    ~StateTileSet ();
    int getCellHeight () const;
    int getCellWidth () const;
    std::string getImageFile ();
    Tile* getCharTile (char character);
    // Setters and Getters
  };

};

#endif
