// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Texture;
  class VertexArray;
};
namespace render {
  class Tile;
};
namespace sf {
  class Drawable;
  class Transformable;
}


namespace render {

  /// class Surface - 
  class Surface : public sf::Drawable, public sf::Transformable {
    // Attributes
  private:
    sf::Texture texture;
    sf::VertexArray quads;
    // Operations
  public:
    void loadTexture (std::string& image_file);
    void initQuads (int count);
    void setSpriteLocation (int nb, int abs, int ord);
    void setSpriteTexture (int nb, Tile* texture);
    void draw (sf::RenderTarget& target, sf::RenderStates states);
    // Setters and Getters
  };

};

#endif
