// Generated by dia2code
#ifndef RENDER__TEXTURESPACK__H
#define RENDER__TEXTURESPACK__H

#include <vector>
#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Texture;
}


namespace render {

  /// class TexturesPack - 
  class TexturesPack {
    // Attributes
  private:
    std::vector<sf::Texture> textures;
    // Operations
  public:
    TexturesPack ();
    sf::Texture getText (int i);
    void loadTextures (std::string& text_file_name, int i);
    std::vector<sf::Texture> getTexturesArray () const;
    // Setters and Getters
  };

};

#endif
