// Generated by dia2code
#ifndef RENDER__TEXTURESPACK__H
#define RENDER__TEXTURESPACK__H

#include <vector>
#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Texture;
}


namespace render {

  /// class TexturesPack - 
  class TexturesPack {
    // Attributes
  private:
    std::vector<sf::Texture> textures;
    // Operations
  public:
    TexturesPack ();
    const sf::Texture& getText (int i);
    const std::vector<sf::Texture>& getTexturesArray () const;
    void setTexturesArray (const std::vector<std::string>& references_array);
    // Setters and Getters
  };

};

#endif
