// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <vector>

namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Attributes
  private:
    std::vector<Tile*> tiles_array;
    // Operations
  public:
    TileSet ();
    virtual ~TileSet ();
    Tile* getTile (int i) const;
    // Setters and Getters
  };

};

#endif
