// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace render {

  /// class Tile - 
  class Tile {
    // Attributes
  private:
    int abs;
    int ord;
    int height     = 16;
    int width     = 16;
    // Operations
  public:
    Tile ();
    Tile (int abs, int ord);
    ~Tile ();
    // Setters and Getters
  };

};

#endif
