// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace status {
  class Element;
}

#include "status/Element.h"
#include "Tile.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Operations
  public:
    virtual ~TileSet ();
    virtual int getCellWidth () const = 0;
    virtual int getCellHeight () const = 0;
    virtual std::string getImageFile () const = 0;
    virtual Tile* getTile (status::Element* element) const;
    virtual Tile* getCharTile (char character) const;
    // Setters and Getters
  };

};

#endif
