// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Attributes
  private:
    std::vector<Tile*> tiles_array;
    // Operations
  public:
    TileSet ();
    ~TileSet ();
    Tile* getTile (int i) const;
    void setTile (std::string& name, int width, int height);
    // Setters and Getters
  };

};

#endif
