// Generated by dia2code
#ifndef STATUS__ELEMENTTAB__H
#define STATUS__ELEMENTTAB__H

#include <stdlib.h>
#include <vector>

namespace status {
  class Element;
}

#include "TypeID.h"
#include "Element.h"

namespace status {

  /// class ElementTab - 
  class ElementTab {
    // Associations
    // Attributes
  private:
    size_t height;
    size_t width;
    std::vector<std::vector<Element*>> array;
    // Operations
  public:
    ElementTab (size_t width, size_t height, TypeID type_id);
    ~ElementTab ();
    size_t const getWidth ();
    size_t const getHeight ();
    Element* const getElement (int i, int j);
    void setElement (int i, int j, Element* element);
    // Setters and Getters
  };

};

#endif
