// Generated by dia2code
#ifndef STATUS__TRANSPORT__H
#define STATUS__TRANSPORT__H


namespace status {
  class Unit;
}

#include "TypeTransport.h"
#include "Unit.h"

namespace status {

  /// class Transport - 
  class Transport : public status::Unit {
    // Associations
    // Attributes
  private:
    int maximumCharge;
    int onBoard;
    TypeTransport type_transport;
    // Operations
  public:
    Transport (int abs, int ord, TypeTransport type_transport);
    ~Transport ();
    int const getOnBoard ();
    int const getMaximumCharge ();
    void setMaximumCharge (int charge);
    // Setters and Getters
  };

};

#endif
