// Generated by dia2code
#ifndef STATUS__TYPELAND__H
#define STATUS__TYPELAND__H


namespace status {

  enum TypeLand {
    BUILDING     = 0,
    FOREST     = 1,
    MOUNTAIN     = 2,
    PLAIN     = 3,
    SHORE     = 4,
    BEACH     = 5,
    RIVER_MOUTH     = 6,
    SEA     = 7,
    RIVER     = 8,
    REEF     = 9,
    CROSSROAD     = 10,
    ROAD     = 11,
    BRIDGE     = 12
  };

};

#endif
