// Generated by dia2code
#ifndef STATUS__TYPECOMMANDER__H
#define STATUS__TYPECOMMANDER__H


namespace status {

  enum TypeCommander {
    REPAIR     = 0,
    MAX_POWER     = 1,
    FORCED_WALK     = 2,
    BLIZZARD     = 3,
    AMBUSH     = 4
  };

};

#endif
