// Generated by dia2code
#ifndef STATUS__TYPEBUILDING__H
#define STATUS__TYPEBUILDING__H


namespace status {

  enum TypeBuilding {
    TOWN     = 0,
    HQ     = 1,
    PORT     = 2,
    FACTORY     = 3,
    AIRPORT     = 4
  };

};

#endif
