// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>
#include <random>

namespace engine {
  class Command;
  class Engine;
}

#include "engine/Engine.h"
#include "engine/Command.h"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  private:
    std::vector<engine::Command*> list;
    // Operations
  public:
    virtual void run (engine::Engine* engine) = 0;
    void setlist (std::vector<engine::Command*> listarg);
    engine::Command* getCommand (std::mt19937& randgen);
    // Setters and Getters
  };

};

#endif
