// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>

namespace engine {
  class Command;
  class Engine;
}

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  private:
    std::vector<engine::Command*> list;
    // Operations
  public:
    virtual void run (engine::Engine* engine) = 0;
    void setlist (std::vector<engine::Command*> listarg);
    // Setters and Getters
  };

};

#endif
