// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <string>
#include <vector>

namespace engine {
  class Engine;
  class Command;
}

#include "engine/Engine.h"
#include "engine/Command.h"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  private:
    std::vector<std::string> list;
    // Operations
  public:
    virtual void run (engine::Engine* engine) = 0;
    engine::Command* getCommand (int i, int j, int height, int width) const;
    void addCommand (std::string& command);
    // Setters and Getters
  };

};

#endif
