// Generated by dia2code
#ifndef AI__DEEPAI__H
#define AI__DEEPAI__H

#include "status.h"

namespace ai {
  class PathMap;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "PathMap.h"
#include "AI.h"

namespace ai {

  /// class DeepAI - 
  class DeepAI : public ai::AI {
    // Associations
    // Attributes
  private:
    PathMap building_map;
    PathMap adv_units_map;
    PathMap qg_map;
  protected:
    int maxDepth     = 4;
    // Operations
  public:
    DeepAI (const status::State& state);
    void run (engine::Engine* engine);
  protected:
    int minmax_rec (engine::Engine& engine, Direction& bestdir, int depth);
    // Setters and Getters
    int getMaxDepth() const;
    void setMaxDepth(int maxDepth);
  };

};

#endif
