// Generated by dia2code
#ifndef AI__DIRECTION__H
#define AI__DIRECTION__H


namespace ai {

  enum Direction {
    NORTH     = 0,
    SOUTH     = 1,
    EAST     = 2,
    WEST     = 3
  };

};

#endif
