// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H


namespace ai {
  class PathMap;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "PathMap.h"
#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Associations
    // Attributes
  private:
    PathMap adv_units_map;
    PathMap building_map;
    // Operations
  public:
    HeuristicAI ();
    const PathMap& getAdvUnitsMap () const;
    const PathMap& getBuildingMap () const;
    void run (engine::Engine* engine);
    // Setters and Getters
  };

};

#endif
