// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <vector>

namespace ai {
  class PathMap;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
  class Point;
}

#include "PathMap.h"
#include "status/TEAM.h"
#include "AI.h"
#include "Point.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Associations
    // Attributes
  private:
    std::vector<PathMap> units_map;
    std::vector<PathMap> buildings_map;
    // Operations
  public:
    HeuristicAI ();
    const PathMap& getAdvUnitsMap (status::TEAM team) const;
    const PathMap& getBuildingMap (status::TEAM team) const;
    void run (engine::Engine* engine);
    // Setters and Getters
  };

};

#endif
