// Generated by dia2code
#ifndef AI__PCOMPW__H
#define AI__PCOMPW__H


namespace ai {
  class Point;
}

#include "Point.h"

namespace ai {

  /// class PcompW - 
  class PcompW {
    // Operations
  public:
    bool operator() (const Point& a, const Point& b);
    // Setters and Getters
  };

};

#endif
