// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H


namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Attributes
  private:
    int randgen;
    // Operations
  public:
    RandomAI (int randomSeed);
    void run (engine::Engine* engine);
    void set_randgen (int randomSeed);
    // Setters and Getters
  };

};

#endif
