// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H

#include "status.h"

namespace status {
  class State;
}

namespace engine {

  /// class Action - 
  class Action {
    // Operations
  public:
    virtual void apply (status::State* state);
    virtual void undo (status::State* state);
    // Setters and Getters
  };

};

#endif
