// Generated by dia2code
#ifndef ENGINE__ATTACKCHARCOMMAND__H
#define ENGINE__ATTACKCHARCOMMAND__H


namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class AttackCharCommand - 
  class AttackCharCommand : public engine::Command {
    // Operations
  public:
    AttackCharCommand ();
    ~AttackCharCommand ();
    AttackCharCommand (status::Unit* shooter, status::Unit* receiver);
    CommandTypeId getTypeId () const;
    // Setters and Getters
  };

};

#endif
