// Generated by dia2code
#ifndef ENGINE__ATTACKCHARCOMMAND__H
#define ENGINE__ATTACKCHARCOMMAND__H


namespace status {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class AttackCharCommand - 
  class AttackCharCommand : public engine::Command {
    // Attributes
  private:
    int character;
    // Operations
  public:
    AttackCharCommand (int c);
    CommandTypeId getTypeId () const;
    void execute (status::State& state);
    // Setters and Getters
  };

};

#endif
