// Generated by dia2code
#ifndef ENGINE__CAPTUREBUILDING__H
#define ENGINE__CAPTUREBUILDING__H

#include <stack>
#include "status.h"

namespace engine {
  class Action;
};
namespace status {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class CaptureBuilding - 
  class CaptureBuilding : public engine::Command {
    // Attributes
  protected:
    int height;
    int width;
    // Operations
  public:
    CaptureBuilding (int height, int width);
    ~CaptureBuilding ();
    CommandTypeID getTypeID () const;
    void execute (std::stack<Action*>& actions, status::State* state);
    // Setters and Getters
    int getHeight() const;
    void setHeight(int height);
    int getWidth() const;
    void setWidth(int width);
  };

};

#endif
