// Generated by dia2code
#ifndef ENGINE__CAPTUREBUILDINGACTION__H
#define ENGINE__CAPTUREBUILDINGACTION__H

#include <memory>
#include "status.h"

namespace status {
  class Element;
  class State;
};
namespace engine {
  class Action;
}

#include "status/Element.h"
#include "Action.h"

namespace engine {

  /// class CaptureBuildingAction - 
  class CaptureBuildingAction : public engine::Action {
    // Attributes
  private:
    std::unique_ptr<status::Element> prevbuilding;
  protected:
    int height;
    int width;
    // Operations
  public:
    CaptureBuildingAction (int height, int width);
    void apply (status::State* state);
    void undo (status::State* state);
    // Setters and Getters
    int getHeight() const;
    void setHeight(int height);
    int getWidth() const;
    void setWidth(int width);
  };

};

#endif
