// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H


namespace status {
  class Element;
  class ElementTab;
  class State;
}

#include "CommandTypeId.h"
#include "status/Element.h"
#include "status/ElementTab.h"
#include "status/State.h"

namespace engine {

  /// class Command - 
  class Command {
    // Operations
  public:
    virtual ~Command ();
    virtual CommandTypeId getTypeId () const = 0;
    // Setters and Getters
  };

};

#endif
