// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeID {
    LOAD     = 1,
    CREATE     = 2,
    MOVE     = 3,
    ATTACK     = 4,
    CAPTURE     = 5
  };

};

#endif
