// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    LOAD     = 1,
    SELECT_CHAR     = 2,
    MOVE_CHAR     = 3,
    ATTACK     = 4,
    CREATE_CHARACTER     = 5,
    WILD_COLLISION     = 6,
    HANDLE_BUILDING     = 7
  };

};

#endif
