// Generated by dia2code
#ifndef ENGINE__CREATECHARACTERCOMMAND__H
#define ENGINE__CREATECHARACTERCOMMAND__H


namespace status {
  class ElementTab;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class CreateCharacterCommand - 
  class CreateCharacterCommand : public engine::Command {
    // Operations
  public:
    CreateCharacterCommand ();
    ~CreateCharacterCommand ();
    CreateCharacterCommand (status::Building* factory, status::ElementTab* units_tab);
    CommandTypeId getTypeId () const;
    // Setters and Getters
  };

};

#endif
