// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <string>

namespace status {
  class State;
}

#include "status/State.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  private:
    status::State* state;
    // Operations
  public:
    Engine (std::string& file_name);
    ~Engine ();
    void createUnit (status::TypeUnits type_unit, int height, int width);
    void moveUnit (int height_start, int width_start, int height_end, int width_end);
    void attackUnit (int height_shooter, int width_shooter, int height_target, int width_target);
    void captureBuilding (int height, int width);
    status::State* getState () const;
    void setState (status::State* new_state);
    // Setters and Getters
  };

};

#endif
