// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <map>
#include <memory>

namespace status {
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  private:
    std::map<int,std::unique_ptr<Command>> currentCommands;
    status::State* currentState;
    // Operations
  public:
    Engine ();
    ~Engine ();
    status::State* getState () const;
    void addCommand (int priority, Command* cmd);
    void update ();
    void setCurrentState (status::State* state);
    // Setters and Getters
  };

};

#endif
