// Generated by dia2code
#ifndef ENGINE__HANDLEATTACKCOMMAND__H
#define ENGINE__HANDLEATTACKCOMMAND__H


namespace status {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class HandleAttackCommand - 
  class HandleAttackCommand : public engine::Command {
    // Attributes
  private:
    int character;
    int target;
    // Operations
  public:
    int attackTarget (status::State& state, int target, int character);
    killTarget (status::State& state, int target);
    killCharacter (status::State& state, int character);
    CommandTypeId getTypeId () const;
    void execute (status::State& state);
    // Setters and Getters
  };

};

#endif
