// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H

#include <string>

namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class LoadCommand - 
  class LoadCommand : public engine::Command {
    // Attributes
  private:
    std::string file_name;
    // Operations
  public:
    LoadCommand ();
    ~LoadCommand ();
    LoadCommand (const char* f);
    CommandTypeId getTypeId () const;
    // Setters and Getters
  };

};

#endif
