// Generated by dia2code
#ifndef ENGINE__LOADMAP__H
#define ENGINE__LOADMAP__H

#include <string>
#include <stack>
#include <memory>
#include "status.h"

namespace engine {
  class Action;
};
namespace status {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Action.h"
#include "Command.h"

namespace engine {

  /// class LoadMap - 
  class LoadMap : public engine::Command {
    // Attributes
  private:
    std::string file_name;
    // Operations
  public:
    LoadMap (const std::string& file_name);
    ~LoadMap ();
    CommandTypeID getTypeID () const;
    void execute (std::stack<std::shared_ptr<Action> >& actions, status::State* state);
    // Setters and Getters
  };

};

#endif
