// Generated by dia2code
#ifndef ENGINE__LOADMAP__H
#define ENGINE__LOADMAP__H

#include <string>
#include <stack>
#include "status.h"
#include <json/json.h>

namespace engine {
  class Action;
};
namespace status {
  class State;
};
namespace engine {
  class LoadMap;
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class LoadMap - 
  class LoadMap : public engine::Command {
    // Attributes
  private:
    std::string file_name;
    // Operations
  public:
    LoadMap (const std::string& file_name);
    ~LoadMap ();
    CommandTypeID getTypeID () const;
    void execute (std::stack<Action*>& actions, status::State* state);
    void serialize (Json::Value& out) const;
    LoadMap* deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
