// Generated by dia2code
#ifndef ENGINE__MOVEUNIT__H
#define ENGINE__MOVEUNIT__H

#include "status.h"

namespace status {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class MoveUnit - 
  class MoveUnit : public engine::Command {
    // Attributes
  protected:
    int height;
    int width;
    // Operations
  public:
    MoveUnit (int height, int width);
    CommandTypeID getTypeID () const;
    void execute (status::State& state);
    // Setters and Getters
    int getHeight() const;
    void setHeight(int height);
    int getWidth() const;
    void setWidth(int width);
  };

};

#endif
