// Generated by dia2code
#ifndef ENGINE__MOVECHARCOMMAND__H
#define ENGINE__MOVECHARCOMMAND__H


namespace status {
  class ElementTab;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class MoveCharCommand - 
  class MoveCharCommand : public engine::Command {
    // Operations
  public:
    MoveCharCommand ();
    MoveCharCommand (status::ElementTab* unit_tab, status::Land* destination, status::Unit* unit_to_move);
    ~MoveCharCommand ();
    CommandTypeId getTyepId () const;
    // Setters and Getters
  };

};

#endif
