// Generated by dia2code
#ifndef ENGINE__MOVEUNITACTION__H
#define ENGINE__MOVEUNITACTION__H

#include "status.h"

namespace status {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class MoveUnitAction - 
  class MoveUnitAction : public engine::Action {
    // Attributes
  protected:
    int height_start;
    int width_start;
    int height_end;
    int width_end;
    // Operations
  public:
    MoveUnitAction (int height_start, int width_start, int height_end, int width_end);
    void apply (status::State* state);
    void undo (status::State* state);
    // Setters and Getters
    int getHeight_start() const;
    void setHeight_start(int height_start);
    int getWidth_start() const;
    void setWidth_start(int width_start);
    int getHeight_end() const;
    void setHeight_end(int height_end);
    int getWidth_end() const;
    void setWidth_end(int width_end);
  };

};

#endif
