// Generated by dia2code
#ifndef ENGINE__MOVECHARCOMMAND__H
#define ENGINE__MOVECHARCOMMAND__H


namespace status {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class MoveCharCommand - 
  class MoveCharCommand : public engine::Command {
    // Attributes
  private:
    int character;
    // Operations
  public:
    MoveCharCommand (int c);
    CommandTypeId getTyepId () const;
    void execute (status::State& state);
    // Setters and Getters
  };

};

#endif
