// Generated by dia2code
#ifndef ENGINE__RESETUNITSACTION__H
#define ENGINE__RESETUNITSACTION__H

#include "status.h"

namespace status {
  class Element;
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"
#include "status/Element.h"

namespace engine {

  /// class ResetUnitsAction - 
  class ResetUnitsAction : public engine::Action {
    // Attributes
  private:
    status::Element* prev_unit;
    // Operations
  public:
    ResetUnitsAction (status::Element* element);
    void apply (status::State* state);
    void undo (status::State* state);
    // Setters and Getters
  };

};

#endif
