// Generated by dia2code
#ifndef ENGINE__RESETUNITSACTION__H
#define ENGINE__RESETUNITSACTION__H

#include <memory>
#include "status.h"

namespace status {
  class Element;
  class State;
};
namespace engine {
  class Action;
}

#include "status/Element.h"
#include "Action.h"

namespace engine {

  /// class ResetUnitsAction - 
  class ResetUnitsAction : public engine::Action {
    // Attributes
  private:
    std::unique_ptr<status::Element> prevunit;
    // Operations
  public:
    ResetUnitsAction ();
    void apply (status::State* state);
    void undo (status::State* state);
    // Setters and Getters
  };

};

#endif
