// Generated by dia2code
#ifndef ENGINE__SELECTCHARCOMMAND__H
#define ENGINE__SELECTCHARCOMMAND__H


namespace status {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class SelectCharCommand - 
  class SelectCharCommand : public engine::Command {
    // Attributes
  private:
    int character;
    // Operations
  public:
    SelectCharCommand (int c, state::Unit u);
    CommandTypeId getTypeId () const;
    void execute (status::State& state);
    // Setters and Getters
  };

};

#endif
