// Generated by dia2code
#ifndef ENGINE__WILDCOLLISIONCOMMAND__H
#define ENGINE__WILDCOLLISIONCOMMAND__H


namespace status {
  class State;
};
namespace engine {
  class Command;
}

#include "status/TypeLand.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class WildCollisionCommand - 
  class WildCollisionCommand : public engine::Command {
    // Attributes
  private:
    int character;
    // Operations
  public:
    WildCollisionCommand (int c, status::TypeLand land);
    CommandTypeId getTypeId () const;
    void execute (status::State& state);
    // Setters and Getters
  };

};

#endif
