// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H

#include <vector>

namespace server {
  class Player;
}

#include "Player.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  public:
    /// 											
    std::vector<Player> players;
    // Operations
  public:
    Game ();
    Player& player (int i);
    // Setters and Getters
  };

};

#endif
