// Generated by dia2code
#ifndef SERVER__PLAYER__H
#define SERVER__PLAYER__H

#include <string>

#include "status/TEAM.h"

namespace server {

  /// class Player - 
  class Player {
    // Attributes
  public:
    std::string name;
    status::TEAM teamcolor;
    bool free     = true;
    // Setters and Getters
  };

};

#endif
