// Generated by dia2code
#ifndef __AI__H
#define __AI__H

#include "ai/AI.h"
#include "ai/RandomAI.h"
#include "ai/Direction.h"
#include "ai/Point.h"
#include "ai/PcompW.h"
#include "ai/PathMap.h"
#include "ai/HeuristicAI.h"
#include "ai/DeepAI.h"
#endif
