// Generated by dia2code
#ifndef ENGINE__ATTACKCHARCOMMAND__H
#define ENGINE__ATTACKCHARCOMMAND__H


namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class AttackCharCommand - 
  class AttackCharCommand : public engine::Command {
    // Attributes
  protected:
    int character;
    // Operations
  public:
    AttackCharCommand (int c);
    CommandTypeId const getTypeId ();
    void execute (state::State& state);
    // Setters and Getters
    int getCharacter() const;
    void setCharacter(int character);
  };

};

#endif
