// Generated by dia2code
#ifndef ENGINE__HANDLEBUILDINGCOMMAND__H
#define ENGINE__HANDLEBUILDINGCOMMAND__H


namespace engine {
  class Command;
}

#include "Command.h"
#include "status/TypeCommander.h"

namespace engine {

  /// class HandleBuildingCommand - 
  class HandleBuildingCommand : public engine::Command {
    // Attributes
  protected:
    int building;
    // Operations
  public:
    int getMoney (status::TypeCommander owner);
    CommandTypeId const getTypeId ();
    void execute (status::State& state);
    // Setters and Getters
    int getBuilding() const;
    void setBuilding(int building);
  };

};

#endif
