// Generated by dia2code
#ifndef ENGINE__HANDLEATTACKCOMMAND__H
#define ENGINE__HANDLEATTACKCOMMAND__H


namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class HandleAttackCommand - 
  class HandleAttackCommand : public engine::Command {
    // Attributes
  protected:
    int character;
    int target;
    // Operations
  public:
    int attackTarget (state::State& state, int target, int character);
    killTarget (state::State& state, int target);
    killCharacter (state::State& state, int character);
    CommandTypeId const getTypeId ();
    void execute (state::State& state);
    // Setters and Getters
    int getCharacter() const;
    void setCharacter(int character);
    int getTarget() const;
    void setTarget(int target);
  };

};

#endif
