// Generated by dia2code
#ifndef ENGINE__SELECTCHARCOMMAND__H
#define ENGINE__SELECTCHARCOMMAND__H


namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class SelectCharCommand - 
  class SelectCharCommand : public engine::Command {
    // Attributes
  public:
    int character;
    // Operations
  public:
    SelectCharCommand (int c, state::Unit u);
    CommandTypeId const getTypeId ();
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
