// Generated by dia2code
#ifndef ENGINE__WILDCOLLISIONCOMMAND__H
#define ENGINE__WILDCOLLISIONCOMMAND__H


namespace engine {
  class Command;
}

#include "Command.h"
#include "status/TypeLand.h"

namespace engine {

  /// class WildCollisionCommand - 
  class WildCollisionCommand : public engine::Command {
    // Attributes
  protected:
    int character;
    // Operations
  public:
    WildCollisionCommand (int c, status::TypeLand l);
    CommandTypeId const getTypeId ();
    void execute (status::State& state);
    // Setters and Getters
    int getCharacter() const;
    void setCharacter(int character);
  };

};

#endif
