// Generated by dia2code
#ifndef STATUS__BUILDING__H
#define STATUS__BUILDING__H


namespace status {
  class Land;
}

#include "TypeBuilding.h"
#include "Land.h"

namespace status {

  /// class Building - 
  class Building : public status::Land {
    // Associations
    // Attributes
  private:
    int tax_inc     = 1000;
    int const healer     = 2;
    int health;
    TypeBuilding type_building;
    // Operations
  public:
    Building (TypeBuilding type_building);
    ~Building ();
    bool canCraft () const;
    int getHealth () const;
    TypeBuilding getType_building () const;
    // Setters and Getters
  };

};

#endif
