// Generated by dia2code
#ifndef STATUS__ELEMENT__H
#define STATUS__ELEMENT__H


namespace status {
  class Element;
}

#include "TypeID.h"

namespace status {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  protected:
    TypeID type_id;
    int width_position;
    int height_position;
    // Operations
  public:
    Element ();
    Element (TypeID id);
    Element (Element* old_element);
    virtual ~Element ();
    virtual bool isStatic () const = 0;
    virtual void affiche () const = 0;
    // Setters and Getters
    TypeID getType_id() const;
    void setType_id(TypeID type_id);
    int getWidth_position() const;
    void setWidth_position(int width_position);
    int getHeight_position() const;
    void setHeight_position(int height_position);
  };

};

#endif
