// Generated by dia2code
#ifndef STATUS__ELEMENTTAB__H
#define STATUS__ELEMENTTAB__H

#include <vector>

namespace status {
  class Element;
}

#include "TypeID.h"

namespace status {

  /// class ElementTab - 
  class ElementTab {
    // Attributes
  private:
    int width;
    int height;
    std::vector<std::vector<Element*>> array;
    // Operations
  public:
    ElementTab (int width, int height, TypeID type_id);
    ~ElementTab ();
    int getWidth () const;
    int getHeight () const;
    Element* getElement (int i, int j);
    void setElement (int i, int j, Element* element);
    // Setters and Getters
  };

};

#endif
