// Generated by dia2code
#ifndef STATUS__LAND__H
#define STATUS__LAND__H


namespace status {
  class Element;
}

#include "TypeLand.h"
#include "Element.h"

namespace status {

  /// class Land - 
  class Land : public status::Element {
    // Associations
    // Attributes
  protected:
    int defense;
    int cost_mvmt;
    TypeLand type_land;
    // Operations
  public:
    Land (int abs, int ord, TypeLand type_land);
    ~Land ();
    bool isBuilding () const;
    bool isStatic () const;
    void affiche () const;
    // Setters and Getters
    int getDefense() const;
    void setDefense(int defense);
    int getCost_mvmt() const;
    void setCost_mvmt(int cost_mvmt);
    TypeLand getType_land() const;
    void setType_land(TypeLand type_land);
  };

};

#endif
