// Generated by dia2code
#ifndef STATUS__STATE__H
#define STATUS__STATE__H

#include <string>
#include <stdlib.h>

namespace status {
  class ElementTab;
}

#include "ElementTab.h"

namespace status {

  /// class State - 
  class State {
    // Associations
    // Attributes
  private:
    ElementTab* lands;
    ElementTab* buildings;
    ElementTab* units;
    std::string text_file_name;
    size_t day;
    size_t timer     = 90;
    int width;
    int height;
    int tile_width;
    int tile_height;
    // Operations
  public:
    State ();
    ~State ();
    void initialisation (std::string& file_name);
    ElementTab* getLands () const;
    ElementTab* getBuildings () const;
    ElementTab* getUnits () const;
    void setDimensions (std::string& text_file_name);
    size_t getDay () const;
    void setDay (size_t day);
    int getHeight () const;
    int getWidth () const;
    // Setters and Getters
  };

};

#endif
