// Generated by dia2code
#ifndef STATUS__STATE__H
#define STATUS__STATE__H

#include <memory>
#include <stdlib.h>

namespace status {
  class ElementTab;
}

#include "ElementTab.h"

namespace status {

  /// class State - 
  class State {
    // Associations
    // Attributes
  private:
    std::unique_ptr<ElementTab> grid;
    std::unique_ptr<ElementTab> units;
    size_t day;
    size_t timer     = 90;
    // Operations
  public:
    State (int width, int height);
    ~State ();
    std::unique_ptr<ElementTab>& getGrid ();
    std::unique_ptr<ElementTab>& getCharacters ();
    // Setters and Getters
  };

};

#endif
