// Generated by dia2code
#ifndef STATUS__TEAM__H
#define STATUS__TEAM__H


namespace status {

  enum TEAM {
    GREY     = 0,
    ORANGE     = 1,
    BLUE     = 2,
    YELLOW     = 3,
    GREEN     = 4
  };

};

#endif
