// Generated by dia2code
#ifndef STATUS__TYPEUNITS__H
#define STATUS__TYPEUNITS__H


namespace status {

  enum TypeUnits {
    TRANSPORT     = 0,
    INFANTRY     = 1,
    MECH     = 2,
    RECON     = 3,
    TANK     = 4,
    TANK_M     = 5,
    ANTI_AIR_TANK     = 6,
    ANTI_AIR_ML     = 7,
    ARTILLERY     = 8,
    ROCKET_L     = 9,
    FIGHTER     = 10,
    BOMBER     = 11,
    DESTROYER     = 12,
    HELICOPTER     = 13
  };

};

#endif
