// Generated by dia2code
#ifndef STATUS__TYPETRANSPORT__H
#define STATUS__TYPETRANSPORT__H


namespace status {

  enum TypeTransport {
    LANDER     = 0,
    APC     = 1,
    CHOPPER     = 2,
    CRUISER     = 3
  };

};

#endif
